[WIP] Adding Branch Labels Auto-associates Project Board
electron/cation pull request #105
Opened 2022-04-17 23:41 UTC by Hanaffi

Hey @codebytere ,
Sorry for this huge delay but things gone crazy.

I tried to manually add card to some project (for ex. `x-18-19`) as a POC but I get error.
I tried to investigate and lookaround but no progress, Can you give a hint please?

![e1](https://user-images.githubusercontent.com/35642947/163736324-6432b2a7-02ff-4605-9539-ba075983a8f4.png)
![e2](https://user-images.githubusercontent.com/35642947/163736325-3f8954c6-e390-4bc5-b797-4c056ed1070d.png)

Checklist: 
- [ ] Find associated projects names
- [ ] Handle case when project isn't created yet
- [ ] Handle case when Unsorted column isn't created yet
- [ ] Handle case when issue gets closed
- [ ] Add specs

Again, my apologize for this huge delay.

2022-04-18 08:19 UTC, codebytere requested changes
Added some comments to point you in the right direction!

2022-04-18 08:19 UTC, codebytere commented on src/add-card-to-project.ts
> +                (el:any) => el.name == "x-18-19"
branch names are always `number-x-y` - something like `x-18-19` would never exist. Examples:

- 17-x-y
- 18-x-y
- 19-x-y

2022-04-18 08:19 UTC, codebytere commented on src/add-card-to-project.ts
> +    probot.on("issues.opened", async (context:Context['octokit']) => {
The association would occur at the point the issue is labeled, not opened - this should be `issues.opened`.

Hooking on this event also gives us access to the specific label that was added - this then tells us which board we would be associating it to. You can pull `label` from `context.payload` to get that information.

2022-04-18 08:19 UTC, codebytere commented on src/add-card-to-project.ts
> +            log('addCardToProject', LogLevel.ERROR, `Something went wrong..`);
Something like:

```
log('addCardToProject', LogLevel.ERROR, 'Unable to associate issue with project board: ', err);
```

is fine.

2022-04-18 08:19 UTC, codebytere commented on src/add-card-to-project.ts
> +                (el:any) => el.name == "x-18-19"
Let's type this more specifically with Octokit

2022-04-18 08:19 UTC, codebytere commented on src/add-card-to-project.ts
> +                // TODO: Create new project if it doesn't exist
We probably wouldn't want to create a new project if it doesn't exist. Logging and bailing is fine:

```
log('addCardToProject', LogLevel.ERROR, `Unable to find project board with name ${name}`);
```
where `name` is the label name that was added to the issue.

2022-04-18 08:19 UTC, codebytere commented on src/add-card-to-project.ts
> +            const unsorted_column = project_columns.find( (el:any) => el.name == "unsorted" );
s/unsorted/Unsorted

2022-05-04 12:44 UTC, Hanaffi commented
Hey @codebytere , Can you please check it if you have time? :)

2022-05-05 14:51 UTC, Hanaffi commented
Hey @codebytere , Can you please check it if you have time? :)

2022-05-11 20:09 UTC, Hanaffi commented
@MarshallOfSound Probably Shelley won't be available. Can you please review this when you have time?

2022-05-16 19:09 UTC, Hanaffi commented
@codebytere Ping

2022-05-27 13:33 UTC, codebytere commented on src/constants.ts
> +export const PROJECT_NAME_REGEX = /^[1-9]+[0-9]*-x-y$/;
This should be something like `BRANCH_NAME_REGEX` since that's more accurate.

2022-05-27 13:46 UTC, codebytere commented on src/add-card-to-project.ts
> +      if (labelName == null) {
We don't need both of these conditionals, and we probably don't want to throw a bespoke error here.

```js
if (!label || !PROJECT_NAME_REGEX.test(label.name)) {
   log('addCardToProject', LogLevel.ERROR, `No project with ${label?.name} exists`);
   return;
}
```

should be sufficient.

2022-05-27 13:47 UTC, codebytere commented on src/add-card-to-project.ts
> +      const { data: projects } = await octokit.projects.listForRepo({ owner, repo });
We can use:
```js
const { data: projects } = await octokit.projects.listForRepo(context.repo({}));
```

here.

2022-05-27 13:48 UTC, codebytere commented on src/add-card-to-project.ts
> +        throw new Error(`Unable to find project board with name ${labelName}`);
we can simply return here as well.

```js
if (!project) {
  log(
    'addCardToProject',
    LogLevel.ERROR,
    `Unable to find project board with name ${label.name}`,
  );
  return;
}
```

2022-05-27 13:48 UTC, codebytere commented on src/add-card-to-project.ts
> +        log('addCardToProject', LogLevel.ERROR, `Unsorted column doesn't exist!`);
Here as well.

```js
      if (!unsortedColumn) {
        log('addCardToProject', LogLevel.ERROR, `Unsorted column doesn't exist!`);
        return;
      }
```

2022-05-27 13:49 UTC, codebytere commented on src/add-card-to-project.ts
> +        content_id: issueNumber, // This is the issue number
These comments can be removed.

2022-05-27 13:51 UTC, codebytere commented
Please also rebase on main and run `npm run prettier:write` on your branch to lint it properly.

2022-09-22 10:33 UTC, codebytere commented
Closing as we have decided to go a different direction with this feature. We appreciate your efforts here, however, as well as your willingness to work with our change requests!

2022-09-22 10:33 UTC, closed without merging